### PR TITLE
Fix: remove localstorage, only use magic link api for auth status

### LINKED ISSUE #1556: User Auth - Remove Localstorage in favor of magic api
Storing in localstorage is unnecessary, @hugomrdias pointed out there the `isLoggedIn` method handles essentially
the same functionality as putting information in localstorage, we can very likely remove it and just use magic links
method to accomplish the same functionality without the duplicated implementation details.

https://magic.link/docs/api-reference/client-side-sdks/web#isloggedin

### PR DESCRIPTION
**Pull request by dashcraft**
Fixes #1556, removes localstorage and _always_ calls magic link to verify user is authenticated.

### CODE REVIEW

File: packages/website/components/navbar.js [hunk 1]
```diff
@@ -31,7 +31,6 @@ export default function Navbar({ bgColor = 'bg-nsorange', logo, user }) {
 
   const logout = useCallback(async () => {
     await getMagic().user.logout()
-    await localStorage.removeItem('nft-user')
     await queryClient.invalidateQueries('magic-user')
```
Comment (the-simian) [inline packages/website/components/navbar.js]: can this be removed?

File: packages/website/lib/magic.js [hunk 2]
```diff
@@ -49,17 +49,11 @@ export async function login(token, type = 'magic', data = {}) {
 
 export async function isLoggedIn() {
   try {
-    const exists = localStorage.getItem('nft-user')
-    if (exists) {
-      return JSON.parse(exists)
-    }
     const meta = await getMagic().user.getMetadata()
```
Comment (the-simian) [inline packages/website/lib/magic.js]: return await getMagic().user.getMetadata() ?

Comment (the-simian) [reply packages/website/lib/magic.js]: (nonblocking suggestion btw)

File: packages/website/pages/_app.js [hunk 3]
```diff
@@ -33,6 +33,7 @@ export default function App({ Component, pageProps }) {
       // @ts-ignore
       Sentry.setUser(user)
     }
+    // @ts-ignore
```
Comment (the-simian) [inline packages/website/pages/_app.js:36]: honestly, we should disable this rule, you shouldn't always need to observe what you call, sometimes you just want to run something once and do []

there are blogs suggesting you move the entire function into useEffect, but I don't personally agree. It can get really big and maybe you want the fn to be transportable.  I think this is just a nonsense warning with no true benefit, IMO.

Comment (the-simian) [reply packages/website/pages/_app.js:36]: nonblocking, just my opinion

**Review by the-simian — APPROVED** [review]
This looks good, thank you!

**Comment by the-simian** [comment]
This works but, tbh this is a bit slower than before. Its 'as fast as it used to be' but... It does seem to be calling more than once. I am assuming it was already doing this beforehand. I think we should investigate that in a followup issue, it might be a red herring or not.

I don't think we should block this, it fixes the problem, its a minor optimization if its calling more than once. Maybe magic link just does that? Worth looking at.

another thing could be if a component is unmounted and remounted, and calls magic link and its inside of a use Effect with [] it could call more than once. So we could look for that too.

**Comment by dashcraft** [comment]
> This works but, tbh this is a bit slower than before. Its 'as fast as it used to be' but... It does seem to be calling more than once. I am assuming it was already doing this beforehand. I think we should investigate that in a followup issue, it might be a red herring or not.
> 
> I don't think we should block this, it fixes the problem, its a minor optimization if its calling more than once. Maybe magic link just does that? Worth looking at.
> 
> another thing could be if a component is unmounted and remounted, and calls magic link and its inside of a use Effect with [] it could call more than once. So we could look for that too.

100%, we probably need to create a control pattern or something, need to investigate in separate ticket.
