### PR TITLE
fix: add incidents to banner

### LINKED ISSUE #1728: Statuspage maintenance banner does not appear for incidents
Think it's the same as https://github.com/web3-storage/web3.storage/issues/1182

### PR DESCRIPTION
**Pull request by johnathonroach**
Fixes #1728
This PR adds incidents notices to the NFT.storage banner. If there is an incident, it will take precedence over maintenance notices.

### CODE REVIEW

File: packages/website/components/layout.js [hunk 1]
```diff
@@ -8,12 +8,19 @@ import { useQuery } from 'react-query'
...
 
   const { data: statusPageData, error: statusPageError } = useQuery(
     'get-statuspage-summary',
     () => getStatusPageSummary()
   )
+
+  const incidents =
+    statusPageData?.incidents.filter(
+      (/** @type {{ resolved_at: string; }} */ incident) =>
+        incident.resolved_at === null
```
Comment (cmunns) [inline packages/website/components/layout.js:21]: Unless we are certain it will be null it can't hurt to check for falsey values including empty string here.

**Review by cmunns — CHANGES_REQUESTED** [review]

File: packages/website/components/layout.js [hunk 2]
```diff
@@ -8,12 +8,22 @@ import { useQuery } from 'react-query'
...
   )
+
+  const incidents =
+    statusPageData?.incidents.filter(
+      (/** @type {{ resolved_at: string; }} */ incident) =>
+        incident.resolved_at === null ||
+        incident.resolved_at === '' ||
+        incident.resolved_at === 'null' ||
+        incident.resolved_at === 'undefined'
+    ) || []
```
Comment (alanshaw) [inline packages/website/components/layout.js:25]:
```suggestion
    (statusPageData?.incidents || []).filter(
      (/** @type {{ resolved_at: string; }} */ incident) => !!incident.resolved_at)
```

**Review by alanshaw — CHANGES_REQUESTED** [review]

**Review by cmunns — APPROVED** [review]
LGTM

**Review by alanshaw — APPROVED** [review]

**Comment by johnathonroach** [comment]
@alanshaw do you know if there is a way we can test a mock incident within the preview environment? The data for prod comes from https://status.nft.storage/api/v2/. I'm curious if there is a staging version of this endpoint to test with before we merge.

**Comment by alanshaw** [comment]
Create a new free statuspage.io account and create a status page that we can wire up to the staging deployment in order to test. Add me as an admin.

**Comment by johnathonroach** [comment]
@alanshaw statuspage account has been created at https://nftstorage-jroach.statuspage.io/api/v2. I have added you as an admin. 

The app is wired up to use the env var `NEXT_PUBLIC_STATUS_PAGE_API` and will fall back to the original endpoint( (https://status.nft.storage/api/v2) when it is not set.
