### PR TITLE
fix: catch more errors

### LINKED ISSUE #986: Invalid tokens should not create p1 alerts in opsgenie.
Magic Admin SDK Error: [ERROR_MALFORMED_TOKEN] might not be the right error to be tracking to generate alerts. If it is, we should verify that the volume of these requests have reached some threshold before error (the alert should specify what this threshold is - probably shouldn't be P1 in either case).

### PR DESCRIPTION
**Pull request by hugomrdias**
This shoud catch more errors and avoid sending them to sentry.

Includes sentry, maintenance and db errors.

closes #986

### CODE REVIEW

File: packages/api/src/utils/auth.js [hunk 1]
```diff
@@ -13,55 +13,47 @@ export const magic = new Magic(secrets.magic)
...
+    const user = await db.getUser(claim.iss)
+    if (user) {
       log.setUser({
-        id: user.data.id,
+        id: user.id,
       })
 
       return {
-        user: user.data,
+        user: user,
```
Comment (alanshaw) [inline packages/api/src/utils/auth.js:51]:
```suggestion
        user,
```

**Review by alanshaw — APPROVED** [review]
Code changes look good, but this **doesn't** close https://github.com/nftstorage/nft.storage/issues/986 correct?

**Comment by hugomrdias** [comment]
> Code changes look good, but this **doesn't** close #986 correct?

this closes 986 because now we dont catch magic errors in auth.js so they bubble up to errors.js and are catched there
